name: instrumented-test

# Controls when the workflow will run
on: [push]

# Controls what will run
jobs:
  #workflow called build checks if project successfully builds
  build:
    runs-on: [macos-latest]
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Run espresso tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86
          disable-animations: true
          script: ./gradlew connectedCheck --stacktrace

      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: instrumentation_test_report
          path: app/build/reports/androidTests/connected/
          files: app/build/outputs/androidTest-results/connected/test-result.pb
