name: linter

# Controls when the workflow will run
on: [push]

# Controls what will run
jobs:
  #workflow called build checks if project coding styles are followed
  build:
    runs-on: [ubuntu-latest]

    steps:
            # Checks-out repository under $GITHUB_WORKSPACE
            - uses: actions/checkout@v2
            # Setup JDK
            - name: Set up JDK 11
              uses: actions/setup-java@v1
              with:
                  java-version: 11
            # Changes Gradle permissions and runs detek Linter
            - name: Grant execute permission for gradlew
              run: chmod +x gradlew
            - name: Lint with Gradle
              run: ./gradlew detekBasic
