name: unit-test

# Controls when the workflow will run
on: [push]

# Controls what will run
jobs:
  #workflow called build checks if project successfully builds
  build:
    runs-on: [ubuntu-latest]

    steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v2
            # Setup JDK
            - name: Set up JDK 11
              uses: actions/setup-java@v1
              with:
                  java-version: 11
            # Changes Gradle permissions and runs test
            - name: Grant execute permission for gradlew
              run: chmod +x gradlew
            - name: Build with Gradle
              run: ./gradlew test
